name: CI/CD Pipeline for Eduathena

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '*'
      - name: Build Docker Image
        run: docker build . -t dufi1928/eduathena:latest
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push dufi1928/eduathena:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login ${{ secrets.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            # Pull the latest images
            sudo docker pull ${{ secrets.DOCKER_REGISTRY }}/eduathena:latest
            sudo docker pull traefik:v2.5
            
            # Ensure docker-compose is available
            if [ ! -f "/usr/local/bin/docker-compose" ]; then
              sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # Ensure docker-compose.yml is in the current directory
            if [ ! -f "docker-compose.yml" ]; then
              echo "docker-compose.yml not found, aborting deployment!"
              exit 1
            fi
            
            # Deploy using Docker Compose
            sudo docker-compose -f docker-compose.yml config
            sudo docker stack deploy -c docker-compose.yml eduathena --with-registry-auth
            
            # List services to verify deployment
            sudo docker service ls