name: CI/CD Pipeline for Eduathena

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '*'
      - name: Build Docker Image
        run: docker build . -t dufi1928/eduathena:latest
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push dufi1928/eduathena:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ivan/deployments/"
          port: 2222  # Spécifier le port ici
      - name: Setup SSH for Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222  # Spécifier le port ici aussi
          script: |
            # Navigate to the directory containing docker-compose.yml
            cd /home/ivan/deployments
            
            # Login to Docker Registry
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login ${{ secrets.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            # Pull the latest images
            sudo docker pull ${{ secrets.DOCKER_REGISTRY }}/eduathena:latest
            sudo docker pull traefik:v2.5
            
            # Deploy using Docker Compose
            sudo docker-compose -f docker-compose.yml config
            sudo docker stack deploy -c docker-compose.yml eduathena --with-registry-auth
            
            # List services to verify deployment
            sudo docker service ls
